### ISSUE TITLE
2.0.0 release failed

### ISSUE THREAD

**Issue by smortex** [ccin2p3/puppet-riemann#22]
The 2.0.0 release failed with a "401 Unauthorized" error:
https://github.com/ccin2p3/puppet-riemann/actions/runs/6040927762/job/16392797381

This is likely due to the `PUPPET_FORGE_USERNAME` or `PUPPET_FORGE_API_KEY` not being available to the repository:

https://github.com/ccin2p3/puppet-riemann/blob/84ac0d102b0d93c193ccd633635445ee274afd13/.github/workflows/release.yml#L21-L22

They can be set directly in the repo, or at the organization level where it is easier to enable them for new repos for the administrator.

When done, clicking on "Re-run jobs" on the failure page should succeed and make the new version available on the Puppet forge.

Thanks!

**Comment by faxm0dem** [comment]
Done !
